In [1]:
!pip install faiss-cpu
!pip install sentence_transformers

   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/14.5 MB 487.6 kB/s eta 0:00:30
    --------------------------------------- 0.3/14.5 MB 3.0 MB/s eta 0:00:05
   -- ------------------------------------- 0.9/14.5 MB 6.6 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/14.5 MB 8.6 MB/s eta 0:00:02
   ------ --------------------------------- 2.3/14.5 MB 9.6 MB/s eta 0:00:02
   ------ --------------------------------- 2.3/14.5 MB 9.6 MB/s eta 0:00:02
   ------ --------------------------------- 2.4/14.5 MB 7.2 MB/s eta 0:00:02
   ------- -------------------------------- 2.8/14.5 MB 7.3 MB/s eta 0:00:02
   -------- ------------------------------- 3.0/14.5 MB 7.1 MB/s eta 0:00:02
   -------- ------------------------------- 3.2/14.5 MB 6.7 MB/s eta 0:00:02
   --------- ------------------------------ 3.4/14.5 MB 6.5 MB/s eta 0:00:02
   --------

In [2]:
import pandas as pd 
pd.set_option('display.max_colwidth',100)

In [3]:
df=pd.read_csv('sample_text.csv')
df.shape

(8, 2)

In [4]:
df

text category
0                                        Meditation and yoga can improve mental health   Health
1                     Fruits, whole grains and vegetables helps control blood pressure   Health
2                                    These are the latest fashion trends for this week  Fashion
3                                    Vibrant color jeans for male are becoming a trend  Fashion
4                                                   The concert starts at 7 PM tonight    Event
5                      Navaratri dandiya program at Expo center in Mumbai this october    Event
6                                    Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   Travel

In [6]:
from sentence_transformers import SentenceTransformer
encoder=SentenceTransformer('all-mpnet-base-v2')
vectors=encoder.encode(df.text)
vectors.shape

C:\Users\Aakarsh Roy\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


(8, 768)

In [7]:
vectors

array([[-0.00247395,  0.03626722, -0.0529046 , ..., -0.09152357,
        -0.03970001, -0.0433049 ],
       [-0.03357267,  0.00980516, -0.03250129, ..., -0.05165466,
         0.02245887, -0.03156181],
       [-0.01865323, -0.04051314, -0.01235388, ...,  0.00610586,
        -0.07179647,  0.0277385 ],
       ...,
       [-0.00066457,  0.04252129, -0.05645508, ...,  0.01315471,
        -0.03183567, -0.04357663],
       [-0.03317155,  0.03252455, -0.02484839, ...,  0.01174421,
         0.05747127,  0.00571023],
       [-0.00166394,  0.00413829, -0.04597083, ...,  0.02008526,
         0.05656243, -0.00161595]], dtype=float32)

In [8]:
dim=vectors.shape[1]
dim

768

In [9]:
import faiss
index=faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001B0B23FDA10> >

In [10]:
index.add(vectors)

In [11]:
search_query="I want to buy a polo tshirt"
vec=encoder.encode(search_query)
vec.shape

(768,)

In [12]:
import numpy as np 
svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [13]:
dist, i=index.search(svec,k=2)
i

array([[2, 3]], dtype=int64)

In [15]:
df.loc[[2,3]]

text category
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion

In [24]:
search_query2="Eat apple and keep the doctor away"
vec=encoder.encode(search_query2)
vec.shape

(768,)

In [25]:
import numpy as np 
svec=np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [26]:
dist, i=index.search(svec,k=2)
i

array([[1, 0]], dtype=int64)

In [27]:
df.loc[[1,0]]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health